name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.5'

    - uses: actions/checkout@v1
    - name: run CI script
      run: |
        sudo apt-get install python-tk python3-tk tk-dev
        pip install -r requirements.txt
        ./.ci/run.sh
