name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: run CI script
      run: |
        pip install -r requirements.txt
        ./.ci/run.sh
